export { CONTRACT_REGISTRY_AMOY_DEFAULT, CONTRACT_REGISTRY_CARDONA_DEFAULT } from './constants'
export * from './create'
export * from './did'
export { KeyPair, DelegateTypes } from 'ethr-did'
export * from 'ethr-did-resolver'